name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Lint with pylint
        run: poetry run pylint src/digitalcorpora_app

      - name: Prepare test credentials
        run: |
          touch etc/credentials.ini
          echo "[dbreader]" >> etc/credentials.ini
          echo "MYSQL_HOST: ${{ secrets.MYSQL_HOST }}" >>  etc/credentials.ini
          echo "MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}" >> etc/credentials.ini
          echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}" >> etc/credentials.ini
          echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}" >> etc/credentials.ini

      - name: Test with pytest and coverage
        run: poetry run pytest --cov --cov-report=term-missing --cov-report=html

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          verbose: true
