# See https://docs.github.com/en/actions/guides/building-and-testing-python
# 2020-02-20 slg - For Dreamhost, we are now using Python 3.9 and Ubuntu-18.04
name: CI (pip)
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          make venv
          find venv -ls
          make install-ubuntu

      - name: Lint with pylint
        run: |
          make pylint

      - name: Test with pytest and a functioning database
        run: |
          touch etc/credentials.ini
          echo "[dbreader]" >> etc/credentials.ini
          echo "MYSQL_HOST: ${{ secrets.MYSQL_HOST }}" >>  etc/credentials.ini
          echo "MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}" >> etc/credentials.ini
          echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}" >> etc/credentials.ini
          echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}" >> etc/credentials.ini
          echo === credentials.ini ===
          cat etc/credentials.ini
          echo =======================
          pip install pytest
          make coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          verbose: true
